theme: jekyll-theme-cayman
title: Deep Learning Match Correspondance in Vegetation Point Clouds
description: Implementation of deep Siamese ConvNet for similarity prediction i.e. match correspondance for reconstruction
